{% set name = "pyacvd" %}
{% set version = "0.2.7" %}

package:
  name: pyacvd
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyacvd-{{ version }}.tar.gz
  sha256: b4eb465b7ce6807b83273ceac9acb8510c4d816f2d0f8a521100222a86935d82

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cython
    - python
  host:
    - cython
    - numpy
    - pip
    - python
    - glew
  run:
    - python
    - pyvista >=0.23.0
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyacvd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyvista/pyacvd
  summary: Uniformly remeshes surface meshes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaszynski
