{% set name = "pyacvd" %}
{% set version = "0.2.8" %}

package:
  name: pyacvd
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyacvd-{{ version }}.tar.gz
  sha256: 85020621c03f87fe1b593056b7e7270b866ff0b21f9cd9505472e895c320fb6b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cython
    - python
  host:
    - cython
    - numpy
    - pip
    - python
    - glew
  run:
    - python
    - pyvista >=0.23.0
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyacvd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyvista/pyacvd
  summary: Uniformly remeshes surface meshes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaszynski
